# App packages related CMakeLists.txt for nrf52833DK
add_subdirectory(package_main)
add_subdirectory(package_led_ctrl)
add_subdirectory(package_ble_adv_demo)
add_subdirectory(package_adv_conn_demo)
add_subdirectory(package_ble_scan_conn_demo)
add_subdirectory(package_mcu_transport)
add_subdirectory(package_sem)
add_subdirectory(package_kmsq)
add_subdirectory(package_kmutex)
add_subdirectory(package_atomic)
add_subdirectory(package_gatt_server_demo)
# BLE OTA production packages
add_subdirectory(package_ble_core)
add_subdirectory(package_ble_adv)
add_subdirectory(package_ble_conn)
add_subdirectory(package_ble_gatt_service)
add_subdirectory(package_ble_gatt_ota_service)
add_subdirectory(package_ble_gatt_client)
add_subdirectory(package_ble_led_ctrl_service)