# 启用日志功能
CONFIG_LOG=y

# 开启同步实时日志输出模式（即写即出）
CONFIG_LOG_MODE_IMMEDIATE=y

# 启用GPIO
CONFIG_GPIO=y

# 开启SPI总线驱动
CONFIG_SPI=y

# 开启Flash子系统
CONFIG_FLASH=y

# 开启JEDEC标准的SPI NOR Flash驱动
CONFIG_SPI_NOR=y

# 开启文件系统与littlefs的支持
CONFIG_FILE_SYSTEM=y
CONFIG_FILE_SYSTEM_LITTLEFS=y

# 开启 Flash 映射子系统（解析设备树里的 fixed-partitions 必备）
CONFIG_FLASH_MAP=y

# 开启 Flash 页面布局查询（LittleFS 需要靠它自动获取 W25Q128 的 4KB 扇区大小）
CONFIG_FLASH_PAGE_LAYOUT=y

# 增加主线程栈大小
CONFIG_MAIN_STACK_SIZE=4096

# 开启线程名称打印
CONFIG_THREAD_NAME=y