# Logging
CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y

# Hardware packages
CONFIG_PACKAGE_LED=y
# CONFIG_PACKAGE_KEY is disabled until key hardware is wired

# Application modules
CONFIG_PACKAGE_LED_CTRL=y
CONFIG_PACKAGE_BLE_ADV_DEMO=n
CONFIG_PACKAGE_BLE_SCAN_CONN_DEMO=y
CONFIG_PACKAGE_SEM_DEMO=n
CONFIG_PACKAGE_KMSQ_DEMO=n
CONFIG_PACKAGE_KMUTEX_DEMO=n

# Bluetooth
CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_CENTRAL=y
CONFIG_BT_DEVICE_NAME="nRF52833 BLE Demo"
CONFIG_BT_RX_STACK_SIZE=4096

# Thread analyze
CONFIG_THREAD_NAME=y
CONFIG_THREAD_ANALYZER=y
CONFIG_THREAD_ANALYZER_AUTO=y